### ISSUE TITLE
JWT/JWS/JWE implementation

### ISSUE THREAD

**Issue by CBenoit** [RustCrypto/meta#13]
Hi!

I see you reserved the name for a "Json Web Encryption" crate: https://crates.io/crates/jwe

Did you already have a plan for it?

I happen to have implemented [a subset of JOSE specification](https://github.com/Devolutions/picky-rs/tree/master/picky/src/jose), notably [JWE](https://github.com/Devolutions/picky-rs/blob/master/picky/src/jose/jwe.rs), as part of my job in [picky crate](https://github.com/Devolutions/picky-rs/tree/master/picky).

We are in the process of improving the JWE implementation with @zer0x64 (who contributed [Deoxys crate](https://github.com/RustCrypto/AEADs/pull/311) in the past), and we thought maybe we could also move it under RustCrypto in the same move. Indeed, we have similar requirements (portable code for one) and already are happy users of a few RustCrypto crates.

`picky` is licensed under `MIT OR Apache-2.0` and my company is okay with me pulling out some components and spending some time improving it in order to integrate in the wider Rust ecosystem. 

I’m open to sending the JWT and JWS pieces as well.

Let me know what you think!

Cheers!

**Comment by Erik1000** [comment]
@CBenoit there has just been a push for JOSE (which JWE is a part of) from @npmccallum via https://github.com/RustCrypto/JOSE/pull/1. Please have a look at my comment over there. Maybe we can join forces? I have also reserved the `jose` crate on crates.io.

**Comment by CBenoit** [comment]
> @CBenoit there has just been a push for JOSE (which JWE is a part of) from @npmccallum via [RustCrypto/JOSE#1](https://github.com/RustCrypto/JOSE/pull/1). Please have a look at my comment over there. Maybe we can join forces? I have also reserved the `jose` crate on crates.io.

Hi @Erik1000 , sure! Did you hear anything from @npmccallum yet?

**Comment by npmccallum** [comment]
I was hoping to push the code yesterday, but discovered a minor issue. I'm hoping to push it today. It currently is a single crate called `jose` with JWK and JWS implementations. No JWE yet.

**Comment by CBenoit** [comment]
Great, I’ll simply open PRs to help push forward the effort when you initial code lands =)

**Comment by npmccallum** [comment]
My PR is open: https://github.com/RustCrypto/JOSE/pull/2
