### ISSUE TITLE
Rust CryptoPAn implementation

### ISSUE THREAD

**Issue by mikemcdermottredjack** [RustCrypto/meta#14]
Sorry to add this issue here, if that is wrong, but I don't see a better place for it. 

We have an implementation of the CryptoPAn algorithm (primarily used for IP address anonymization) (https://en.wikipedia.org/wiki/Crypto-PAn) in Rust that we'd like to contribute to RustCrypto. There are no other Rust implementations of this algorithm that I could find (implementations exist for C++, GO, and Python). 

We have demonstrably working code for IPv4 addresses. I'm happy to submit a PR under whichever repo is most appropriate (a new one might need to be created?)

Thanks

**Comment by newpavlov** [comment]
Hm, I think we can start with the [utils repository](https://github.com/RustCrypto/utils). Later we may move it somewhere else.

**Comment by tarcieri** [comment]
This has an open PR at https://github.com/RustCrypto/formats/pull/861
