### ISSUE TITLE
Where to put PQcrypto projects?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/meta#20]
I've managed to secure the `kyber` and `dilithium` crate names.

The question is where to put them? Should we have a central https://github.com/RustCrypto/PQcrypto repository exclusively focused on post-quantum cryptography, or should we factor the PQcrypto projects into separate repos by algorithm type, e.g.:

- `dilithium` would go in https://github.com/rustcrypto/signatures
- `kyber` would go in a hypothetical new https://github.com/rustcrypto/KEMs

**Comment by tarcieri** [comment]
Personally I'm kinda torn on this.

Factoring everything up by algorithm type is probably the cleanest way to organize things, but I can see organizational advantages to having all of the PQcrypto projects in the same place, i.e. it aids discoverability and collaboration, and makes it clear we're working on (or at least plan to work on) pure Rust post-quantum crypto projects.

**Comment by newpavlov** [comment]
I am fine with both options, but slightly in favor of following the current approach of splitting repositories by algorithm types. Can we expect that PQ algorithms will fit into either signatures, or KEM repository?

We also could create a repository for PQ, but use it only for linking to specific crates from other repositories.

**Comment by tarcieri** [comment]
KEMs and signatures seem like the major things for now, yes.

Okay, let's create a KEMs repo

**Comment by dsprenkels** [comment]
I would be happy to contribute my implementation of Dilithium (after a bit of polishing perhaps). :)

**Comment by tarcieri** [comment]
@dsprenkels awesome! Whenever you're ready, can you open a PR to https://github.com/rustcrypto/signatures ?
