### ISSUE TITLE
Hazmat info

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/meta#3]
@newpavlov I noticed you shut the Wiki off on this repo. There was previously an "About hazmat crates" info page in the Wiki that looked like this:

<img width="946" alt="Screen Shot 2020-07-08 at 10 49 40 AM" src="https://user-images.githubusercontent.com/797/86953138-d5421b80-c108-11ea-8b6b-ffc6bfdbd966.png">

Crates in the block ciphers and stream ciphers repos have badges and a section in their documentation linking to it.

I guess for starters: is this a good central place to put that sort of information? Should it go in a Markdown file in git instead of the Wiki?

(sidebar: I noticed the "hazmat" badge renders poorly on Chrome/iOS and might contain invalid unicode in its current form)

**Comment by newpavlov** [comment]
Ah, sorry! I haven't noticed it while harmonizing settings across repositories. I've reverted the change and luckily the page is still present.

**Comment by tarcieri** [comment]
Yep, it's back:

https://github.com/RustCrypto/meta/wiki/About-%22hazmat%22-crates

I guess the question remains: would it make sense to have a HAZMAT.md or thereabouts in this repo instead?

**Comment by newpavlov** [comment]
I think ideally we should introduce a "book" repository (à la [`rand`](https://github.com/rust-random/book) or [`tokio`](https://github.com/tokio-rs/book)), but until then I guess using wiki in this repo should be fine.

**Comment by tarcieri** [comment]
Added https://github.com/RustCrypto/meta/blob/master/HAZMAT.md and updated links to point to it:

- https://github.com/RustCrypto/block-ciphers/pull/159
- https://github.com/RustCrypto/stream-ciphers/pull/167
