### ISSUE TITLE
Strebog Version Referenced by crypto-hashes has been yanked

### ISSUE THREAD

**Issue by zicklag** [RustCrypto/meta#4]
This prevents building the crate with the `include-weak` feature.

**Comment by newpavlov** [comment]
Ah, his crate hasn't seen much use, so it was essentially unmaintained. I've released `crypto-hashes v0.9`, which uses fixed version of the `streebog` crate.

**Comment by zicklag** [comment]
Ah, yeah, I noticed afterwards that it was just re-exports and realized I could just do that myself. :)

I thought it was adding trait implementations at first.
